# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - redux-refactor
  pull_request:
    branches:
      - redux-refactor

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:  
      matrix: 
        os: ['ubuntu-latest', 'macos-latest']
      fail-fast: false
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - if: matrix.os == 'macos-latest'
      name: We are in macos
      env:
        git_email: ${{ secrets.git_email }}
        git_username: ${{secrets.git_username}}
        git_password: ${{secrets.git_password}}
        MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{secrets.MATCH_GIT_BASIC_AUTHORIZATION}}
        FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
      run: |
        sudo chmod +x .github/workflows/install_mac.sh
        .github/workflows/install_mac.sh

    - if: matrix.os == 'ubuntu-latest'
      name: We are in linux
      run: | 
        sudo chmod +x .github/workflows/install_linux.sh
        .github/workflows/install_linux.sh

    - name: Commit back version bump
      run: |
        git config --global user.name 'Daniel Sudzilouski'
        git config --global user.email 'daniel-sudz@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add .
        git commit -m "Automated version bump"
        git push
