# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - redux-refactor
  pull_request:
    branches:
      - redux-refactor

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy: 
      matrix: 
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
  #  - if: matrix.os = 'macos-latest'
    - name: We are in macos
      run: echo Hello from macos!

 #   - if: matrix.os = 'linux-latest'
    - name: We are in linux
      run: |
        echo hello from linux
        echo hello from linux